name: "CI"
on:
  pull_request:
  push:
    branches:
      - master

env:
  CI: true

jobs:
  Test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [stable, beta]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: UziTech/action-setup-atom@v2
      with:
        version: ${{ matrix.version }}
    - name: Install dependencies
      run: apm install
    - name: Run tests 👩🏾‍💻
      run: atom --test spec

  Lint:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: NPM install
        run: npm install
      - name: Lint ✨
        run: npm run lint

  Release:
    needs: [Test, Lint]
    if: |
      github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: UziTech/action-setup-atom@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: NPM install
        run: npm install
      - name: Release 🎉
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ATOM_ACCESS_TOKEN: ${{ secrets.ATOM_ACCESS_TOKEN }}
        run: npx semantic-release

  Skip:
    if: contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - name: Skip CI 🚫
        run: echo skip ci
